image: node:12.0.0

stages:
  - deploy

transfer_sftp:
  stage: deploy
  script:
    - apt-get update -qq && apt-get install -y -qq lftp sshpass
    - lftp -e "set sftp:auto-confirm yes; mirror -e -P 4 --transfer-all --exclude .git/ --reverse -X .* --verbose ./ /home/ubuntu/andres/pruebas-ci/; quit" -u $USER,$PASSWORD sftp://$HOST -p 222
    - export SSHPASS=$PASSWORD
    - script -qc "sshpass -e ssh -l $USER@$HOST /home/ubuntu/andres/prueba.sh" /dev/null